### ISSUE TITLE
Error running due to change of PIL / pillow package

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2022sp-420-BootSnake#98]
Using python3.9 I get the following error:

```
% python3 bootsnake.py
Traceback (most recent call last):
  File "/Users/wkillian/Desktop/420/BootSnake/bootsnake.py", line 25, in <module>
    from saveLoadModel import *
  File "/Users/wkillian/Desktop/420/BootSnake/saveLoadModel.py", line 19, in <module>
    from canvas import *
  File "/Users/wkillian/Desktop/420/BootSnake/canvas.py", line 20, in <module>
    from PIL import *  # to use PIL import, install pip install Pillow as PIL is deprecated and pillow is the successor
```

I had to run:
```
pip3 install Pillow
```

to resolve

**Comment by bemoran** [comment]
added to readme that pillow is required
